<?xml version="1.0" encoding="utf-8"?><Database Name="Chapter11" Class="LeadDataDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=localhost;Initial Catalog=Chapter11;Integrated Security=True" SettingsObjectName="LeadGenerator.Properties.Settings" SettingsPropertyName="Chapter11ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Lead" Member="Leads">
    <Type Name="Lead">
      <Column Name="LeadID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="WorkflowID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="ContactName" Type="System.String" DbType="VarChar(80) NOT NULL" CanBeNull="false" />
      <Column Name="ContactPhone" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Interests" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Comments" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="AssignedTo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>