<?xml version="1.0" encoding="utf-8"?><Database Name="Appendix" Class="RequestDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=localhost;Initial Catalog=Appendix;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="Request" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Request" Member="Requests">
    <Type Name="Request">
      <Column Name="RequestID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RequestKey" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="RequestType" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="UserEmail" Type="System.String" DbType="VarChar(70)" CanBeNull="true" />
      <Column Name="Comment" Type="System.String" DbType="VarChar(2000)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="QueueInstanceKey" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="ActionTaken" Type="System.String" DbType="VarChar(2000)" CanBeNull="true" />
      <Column Name="RouteNext" Type="System.String" DbType="varchar(50)" CanBeNull="true" />
      <Association Name="QueueInstance_Request" Member="QueueInstance" ThisKey="QueueInstanceKey" OtherKey="QueueInstanceKey" Type="QueueInstance" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.QueueInstance" Member="QueueInstances">
    <Type Name="QueueInstance">
      <Column Name="QueueInstanceID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="QueueInstanceKey" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="InstanceID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CurrentSubQueueID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="QC" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Priority" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AssignedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="AssignedOperatorID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>